[package]
name = "zarrs_conventions"
version = "0.1.0"
edition = "2024"

[dependencies]
iref = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.17"
uuid = { version = "1.19.0", features = ["serde"] }
ctor = { workspace = true }
